#!/bin/bash
#use source or .(dot)
#Script_Path=$(dirname `which $0`) 
Script_Path="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" 
ini_path="${Script_Path}/proxy.ini"
echo $ini_path
if [ $# -eq 0 ]; then
    if [ ! -e  "${ini_path}" ]; then
        echo "proxy.ini missing" 
        return 1
    fi
    conf=( `cat "${ini_path}"` )
    if [ ${#conf} -lt 4 ]; then
        echo "proxy.ini error" 
        return 1
    fi
    addr=${conf[0]}:${conf[1]}@${conf[2]}:${conf[3]}
    export http_proxy=http://${addr}
    export https_proxy=http://${addr}
    export ftp_proxy=http://${addr}
    echo "proxy setted at $addr"
elif [ "$1" = "stop" ]; then
    echo $1
    export http_proxy=
    export https_proxy=
    export ftp_proxy=
    echo "proxy stopped."
else
    echo "command wrong"
fi
